import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join, relative, resolve } from 'node:path';

/**
 * Bakes the built web app into a TypeScript module so the shipped binary can
 * serve the interface itself, with no files next to it and no internet.
 */
const webDist = resolve('../web/dist');
const outFile = resolve('src/generated/web-assets.ts');

async function walk(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) files.push(...(await walk(full)));
    else files.push(full);
  }
  return files;
}

const header = `// Generated by scripts/embed-web.mjs. Do not edit.\n// Source: packages/web/dist\n\n`;

if (!existsSync(join(webDist, 'index.html'))) {
  await mkdir(resolve('src/generated'), { recursive: true });
  await writeFile(outFile, `${header}export const embeddedWeb: Record<string, string> = {};\n`);
  console.log('No web build found, wrote an empty asset map.');
  process.exit(0);
}

const files = await walk(webDist);
const entries = [];
let total = 0;

for (const file of files) {
  // Source maps are for debugging, not worth the binary size.
  if (file.endsWith('.map')) continue;
  const key = `/${relative(webDist, file).split(/[\\/]/).join('/')}`;
  const bytes = await readFile(file);
  total += bytes.length;
  entries.push(`  ${JSON.stringify(key)}: ${JSON.stringify(bytes.toString('base64'))},`);
}

await mkdir(resolve('src/generated'), { recursive: true });
await writeFile(outFile, `${header}export const embeddedWeb: Record<string, string> = {\n${entries.join('\n')}\n};\n`);

console.log(`Embedded ${entries.length} files (${(total / 1024).toFixed(0)} KB) into ${relative(process.cwd(), outFile)}`);
